project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import url
from project import views

app_name = 'project'

urlpatterns = [
    url(r'^view_stock', views.view_stock, name='view_stock'),
    url(r'^$', views.index, name='index'),
    url(r'^index', views.index, name='index'),
    url(r'^help', views.help_page, name='help'),
    # url(r'stock_detail/', views.form_name_view, name='stock_detail')
]

stockProgram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from project import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^project/', include('project.urls')),
]

project/models.py
from django.db import models


# Create your models here.

class Stock(models.Model):
    stock_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.stock_name


class Price(models.Model):
    stock_name = models.ForeignKey(Stock, on_delete=models.DO_NOTHING)
    current_price = models.CharField(max_length=264, unique=True)
    max_price = models.CharField(max_length=264, unique=True)
    min_price = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return '{} {} {} {}'.format(self.stock_name, self.current_price, self.max_price, self.min_price)


class DateRecord(models.Model):
    stock_name = models.ForeignKey(Stock, on_delete=models.DO_NOTHING, )
    date = models.DateField()

    def __str__(self):
        return '{} {}'.format(self.stock_name, str(self.date))


class StockCode(models.Model):
    stock_name = models.ForeignKey(Stock, on_delete=models.DO_NOTHING, )
    code = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return '{} {}'.format(self.stock_name, str(self.code))

# Create table out of this run python manage.py migrate
# Then to migrate to an application run python manage.py migration my app
# and then again run python manage.py migrate to apply the changes

project/forms.py
from django import forms

class FormName(forms.Form):
    stock_name = forms.CharField()

project/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from yahoofinancials import YahooFinancials
from project.models import Stock, Price, DateRecord, StockCode
from .forms import FormName


# Create your views here.


def index(request):
    # return HttpResponse('Hello World!')
    form = FormName(request.POST)
    stock_list = Price.objects.order_by('stock_name')
    stock_code = StockCode.objects.order_by('stock_name')

    final_list = []
    price_dict = {'price_record': stock_list}
    stock_dict = {'stock_record': stock_code}
    print(price_dict)
    print(stock_dict)
    for stock in stock_list:
        stock_data = {'stock_code': stock.stock_name.stock_name, 'Current_price': stock.current_price,
                      'Max_price': stock.max_price, 'Min_price': stock.min_price}
        for stock_c in StockCode.objects.all():
            if stock_c.stock_name.stock_name == stock.stock_name.stock_name:
                stock_data['stock_name'] = stock_c.code
        final_list.append(stock_data)
    print(final_list)

    flag = 'index'
    if request.method == 'POST':
        flag = 'view'
        stock_name = request.POST['stock_name']
        stock = stock_detail(stock_name)
        print(stock['current_price'])
        print(request.method)
        # return render(request, 'project/stock_page.html', context=stock)
        if stock['current_price']:
            #return render(request, 'project/stock_page.html', context=stock)
            return render(request, 'project/index.html', {'dict1': price_dict, 'dict2': final_list, 'dict3': stock_dict,
                                                          'form': form, 'not_found': False, 'flag': flag,
                                                          'stock': stock})
        else:
            return render(request, 'project/index.html', {'dict1': price_dict, 'dict2': final_list, 'dict3': stock_dict,
                                                          'form': form, 'not_found': True, 'flag': flag})
    else:
        return render(request, 'project/index.html', {'dict1': price_dict, 'dict2': final_list, 'dict3': stock_dict,
                                                      'form': form, 'flag': flag})

    # return render(request, 'project/index.html', context=price_dict)


def stock_detail(stock_name):
    stock_dict = {}

    yahoo_financial = YahooFinancials(stock_name)
    current_price = yahoo_financial.get_current_price()
    fifty_two_week_high_value = yahoo_financial.get_yearly_high()
    fifty_two_week_low_value = yahoo_financial.get_yearly_low()

    stock_dict['stock_name'] = stock_name
    stock_dict['high_value'] = fifty_two_week_high_value
    stock_dict['low_value'] = fifty_two_week_low_value
    stock_dict['current_price'] = current_price
    return stock_dict


def view_stock(request):
    if request.method == 'POST':
        stock_name = request.POST['stock_name']
    stock = stock_detail(stock_name)
    not_found = True
    print(stock.current_price)
    print(request.method)
    return render(request, 'project/stock_page.html', context=stock)
    # if stock['current_price']:
    #    return render(request, 'project/stock_page.html', {'stock_detail': stock, 'message': 'Data Available'})
    # else:
    #    return render(request, 'project/index.html', {'message': 'No Data'})


def help_page(request):
    help_content = {'email_id': 'shahrukheqbal@gmail.com'}
    return render(request, "project/help.html", context=help_content)


def form_name_view(request):
    form = FormName()
    stocks = []
    tcs_stock = stock_detail('TCS.NS')
    # principal_stock = stock_detail('PFG')
    # icici_stock = stock_detail('ICICIBANK.NS')
    stocks.append(tcs_stock)
    # stocks.append(principal_stock)
    # stocks.append(icici_stock)

    print(stocks)
    if request.method == 'POST':
        form = FormName(request.POST)
        if form.is_valid():
            # DO SOMETHING CODE
            print("VALIDATION SUCCESSFUL")
            print("Stock Name: " + form.cleaned_data['stock_name'])
            # stock_name = request.POST['stock_name']
            # return render(request, 'project/stock_page.html', context=stock_detail(stock_name))
            # return redirect('project/stock_page.html', context=stock_detail(stock_name))
    # else:
    return render(request, 'project/form_page.html', {'form': form, 'stocks': stocks})

templates/project/form_page.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/> -->
    <title></title>
</head>
<body>
    <div class="container">
        <h1>{{ stocks.stock_name }}</h1><br/><br/>
        <div class="row justify-content-center">
            <form class="" action="{% url 'project:view_stock' %}" method="post">
                {{form}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="submit">
                <br>
                     <div class="stock_price">
                         {% if stocks %}
                         <table class="table table-striped table-bordered">
                             <thead>
                             <th scope="col">StockName</th>
                             <th scope="col">CurrentPrice</th>
                             <th scope="col">52 Week High Price</th>
                             <th scope="col">52 Week Low Price</th>
                             </thead>
                             {% for stock in stocks %}
                             <tr>
                                 <td>{{ stock.stock_name }}</td>
                                 <td>{{ stock.current_price }}</td>
                                 <td>{{ stock.high_value }}</td>
                                 <td>{{ stock.low_value }}</td>
                             </tr>
                             {% endfor %}
                         </table>
                         {% else %}
                         <p> No Stock Records </p>
                         {% endif %}
                     </div>
            </form>
        </div>
        <!-- <div class="container">
            <form class="" action="help" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="help">
            </form>
        </div> -->
    </div>
</body>
</html>

templates/project/help.html
<html>
{% load static %}
<head>
    <title>Stock Market Help Page</title>
    <meta-charset='utf-8'>
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">StockMarket</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'project:index' %}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'project:help' %}"><span ></span> Help</a></li>
    </ul>
  </div>
</nav>
     <div class="jumbotron">
        <h1>Welcome to Help Page</h1>
        Let us know your query at {{ email_id }}<br>
     </div>
    </div>
</body>
</html>

templates/project/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Stock Market</title>
    <meta-charset='utf-8'>
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">StockMarket</a>
            </div>
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'project:index' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'project:help' %}"><span ></span> Help</a></li>
            </ul>
          </div>
        </nav>

    <div class='jumbotron'>
        <h1 text-align="center"> <strong>Welcome to Stock Market</strong></h1>

	<h5><strong>Search by stock Name<strong><br>
        <form class="form-group" width="100%" method="post">
            {{form}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit">
            <br>
        </form>
        </h5>
        {% if not_found %}
            <script>alert('Sorry the stock code is not found')</script>
         {% endif %}

        {% if flag == 'index' %}

            {{ insert_message }}<br>
             <div class="jumbotron">
                 {% if dict1 %}
                 <table class="table table-striped table-bordered" >
                     <thead>
                     <th scope="col">StockCode</th>
                     <th scope="col">StockName</th>
                     <th scope="col">CurrentPrice</th>
                     <th scope="col">52 Week High Price</th>
                     <th scope="col">52 Week Low Price</th>
                     </thead>
                     {% for stock in dict2 %}
                     <tr>
                         <td>{{ stock.stock_code }}</td>
                         <td>{{ stock.stock_name }}</td>
                         <td>{{ stock.Current_price }}</td>
                         <td>{{ stock.Max_price }}</td>
                         <td>{{ stock.Min_price }}</td>
                     </tr>
                     {% endfor %}
                 </table>
                 {% else %}
                 <p> No Stock Records </p>
                 {% endif %}
             </div>
        {% elif flag == 'view' %}
         <div class="jumbotron">
             <!-- <a href="{% url 'project:index' %}">Back</a> -->
             {% if stock.current_price %}
             <table  class="table table-striped table-bordered">
                 <thead>
                 <th scope="col">StockName</th>
                 <th scope="col">CurrentPrice</th>
                 <th scope="col">52 Week High Price</th>
                 <th scope="col">52 Week Low Price</th>
                 </thead>
                 <tr>
                     <td>{{ stock.stock_name }}</td>
                     <td>{{ stock.current_price }}</td>
                     <td>{{ stock.high_value }}</td>
                     <td>{{ stock.low_value }}</td>
                 </tr>
             </table>
             {% else %}
                <div class="jumbotron">
                    <h2 class="h3"> <strong>Don't know the Stock Code? No Worry we have listed top 30 NSE Stocks for you.</strong> </h2>
                     <table class="table table-striped table-bordered">
                         <thead class="thead-dark">
                         <th scope="col">StockCode</th>
                         <th scope="col">StockName</th>
                         </thead>
                         <tbody table-striped>
                         {% for stock in dict3.stock_record %}
                         <tr>
                             <td>{{ stock.stock_name }}</td>
                             <td>{{ stock.code }}</td>
                         </tr>
                         {% endfor %}
                         </tbody>
                     </table>
                </div>
             {% endif %}
             </div>
            <br>
        {% endif %}

        <!--<img src="{% static 'images/stock_market.jpg' %}" alt="Image didn't show up!"> -->
    </div>
</body>
</html>

templates/project/stock_page.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Stock Market</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
</head>
<body>
     <div class="jumbotron">
        <div id="right">
        <form class="form-group" action="{% url 'project:index' %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Back">
            <br>
        </form>
        </div>
         {% if current_price %}
         <table  class="table table-striped table-bordered">
             <thead>
             <th scope="col">StockName</th>
             <th scope="col">CurrentPrice</th>
             <th scope="col">52 Week High Price</th>
             <th scope="col">52 Week Low Price</th>
             </thead>
             <tr>
                 <td>{{ stock_name }}</td>
                 <td>{{ current_price }}</td>
                 <td>{{ high_value }}</td>
                 <td>{{ low_value }}</td>
             </tr>
         </table>
         {% else %}
         <p> No Stock Records </p>
         {% endif %}
     </div>
    <br>
    <!-- Stock_Name: {{stock_name}}<br>
    Stock_Current_Price: {{current_price}}<br>
    Stock_52_Week_High_Price: {{high_value}}<br>
    Stock_52_Week_Low_Price: {{low_value}}<br> -->
</body>

</html>